blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/hatemhosny/diagrams-js/discussions
    about: Please ask and answer questions here
  - name: Documentation
    url: https://diagrams-js.hatemhosny.dev
    about: Check the documentation for usage information
  - name: Security Vulnerability
    url: https://github.com/hatemhosny/diagrams-js/security/advisories/new
    about: Please report security vulnerabilities here
