import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/quickstart",
        "getting-started/examples",
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      items: [
        "guides/diagram",
        "guides/node",
        "guides/edge",
        "guides/clusters",
        "guides/custom-nodes",
        "guides/rendering",
        "guides/json",
        "guides/diagram-diff",
        "guides/migration",
        "guides/providers",
      ],
    },
    {
      type: "category",
      label: "Plugins",
      collapsed: false,
      items: ["plugins/overview", "plugins/docker-compose", "plugins/kubernetes"],
    },
    {
      type: "category",
      label: "Node Reference",
      collapsed: true,
      items: [
        {
          type: "autogenerated",
          dirName: "nodes",
        },
      ],
    },
    "credits",
    "ai-guide",
  ],
};

export default sidebars;
